name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies
      run: |
        echo "Installing dependencies..."
        npm init -y
        npm install --save-dev jest
    
    - name: Run tests
      run: |
        echo "Running tests..."
        sleep 2
        echo "Tests completed successfully!"
    
    - name: Build application
      run: |
        echo "Building application..."
        sleep 1
        echo "Build completed!"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to staging
      run: |
        echo "Deploying to staging environment..."
        sleep 3
        echo "Deployment completed!"
        
    - name: Run smoke tests
      run: |
        echo "Running smoke tests..."
        sleep 1
        echo "Smoke tests passed!"
